"""Update models

Revision ID: 2f2d6f36445a
Revises: 5b193922ece8
Create Date: 2026-01-29 15:05:34.758095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2d6f36445a'
down_revision = '5b193922ece8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
